export const placeholderResults = {
  kind: "youtube#searchListResponse",
  etag: "PQToisF5wA4y05loRGCOTOOwys0",
  nextPageToken: "CAkQAA",
  regionCode: "US",
  pageInfo: {
    totalResults: 1000000,
    resultsPerPage: 9,
  },
  items: [
    {
      kind: "youtube#searchResult",
      etag: "OD3Lb-QNBe7SnfWmKaMLX5yBkqk",
      id: {
        kind: "youtube#video",
        videoId: "5qap5aO4i9A",
      },
      snippet: {
        publishedAt: "2020-02-22T19:51:37Z",
        channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
        title: "lofi hip hop radio - beats to relax/study to",
        description:
          "Thank you for listening, I hope you will have a good time here :) Listen to the playlist on Spotify, Apple music and more → https://bit.ly/chilledcow-playlists ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/5qap5aO4i9A/default_live.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/5qap5aO4i9A/mqdefault_live.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/5qap5aO4i9A/hqdefault_live.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "ChilledCow",
        liveBroadcastContent: "live",
        publishTime: "2020-02-22T19:51:37Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "Dz0OODVb0kSGjXK45HnM8uVRL9E",
      id: {
        kind: "youtube#video",
        videoId: "DWcJFNfaw9c",
      },
      snippet: {
        publishedAt: "2020-02-25T19:00:14Z",
        channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
        title: "lofi hip hop radio - beats to sleep/chill to",
        description:
          "Welcome to the sleepy lofi hip hop radio. This playlist contains the smoothest lofi hip hop beats, perfect to help you chill or fall asleep Listen to the playlist on ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/DWcJFNfaw9c/default_live.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/DWcJFNfaw9c/mqdefault_live.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/DWcJFNfaw9c/hqdefault_live.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "ChilledCow",
        liveBroadcastContent: "live",
        publishTime: "2020-02-25T19:00:14Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "1af8j2Oup0BC4qbIDHXc6Hcf93o",
      id: {
        kind: "youtube#video",
        videoId: "eRCNLqg8wSI",
      },
      snippet: {
        publishedAt: "2020-05-19T16:38:18Z",
        channelId: "UCYVyQv2rUtCMxJAFSuOSpmg",
        title: "Open Your MInd ~ lofi hip hop mix",
        description:
          "Spotify playlist ( Tracks from this mix will be added to this playlist ) ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/eRCNLqg8wSI/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/eRCNLqg8wSI/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/eRCNLqg8wSI/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Dreamy",
        liveBroadcastContent: "none",
        publishTime: "2020-05-19T16:38:18Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "1JrKIWVp_9T7zJ3E5Wug6sIitSo",
      id: {
        kind: "youtube#video",
        videoId: "-FlxM_0S2lA",
      },
      snippet: {
        publishedAt: "2018-03-19T16:27:06Z",
        channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
        title: "Lofi hip hop mix - Beats to Relax/Study to [2018]",
        description:
          "Listen to ChilledCow on Spotify, Apple music and more → https://bit.ly/chilledcow-playlists Check out the ChilledCow merch → https://bit.ly/chilledcow-merch ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/-FlxM_0S2lA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/-FlxM_0S2lA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/-FlxM_0S2lA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "ChilledCow",
        liveBroadcastContent: "none",
        publishTime: "2018-03-19T16:27:06Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "DfENZZ046V9kjTqQOjSYDCZYjZE",
      id: {
        kind: "youtube#video",
        videoId: "GvesyESp9UE",
      },
      snippet: {
        publishedAt: "2020-05-12T11:39:45Z",
        channelId: "UCWzZ5TIGoZ6o-KtbGCyhnhg",
        title:
          "lofi hip-hop beats to quarantine and stay indoors to 🏠 // 24/7",
        description:
          "We've curated this stream with an emphasis on distraction-free music to help you get the most out of your time at home over the coming weeks. Whether you're ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/GvesyESp9UE/default_live.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/GvesyESp9UE/mqdefault_live.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/GvesyESp9UE/hqdefault_live.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "College Music",
        liveBroadcastContent: "live",
        publishTime: "2020-05-12T11:39:45Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "cHsLUYSKMVWLg4DM1MSs7PltE5A",
      id: {
        kind: "youtube#video",
        videoId: "-5KAN9_CzSA",
      },
      snippet: {
        publishedAt: "2020-05-09T14:53:57Z",
        channelId: "UCsIg9WMfxjZZvwROleiVsQg",
        title: "coffee shop radio // 24/7 lofi hip-hop beats",
        description:
          "Coffee Shop Vibes on Spotify: https://fanlink.to/CSVibes This stream's playlist is curated with an emphasis on meditation and relaxation. No vocal samples, just ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/-5KAN9_CzSA/default_live.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/-5KAN9_CzSA/mqdefault_live.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/-5KAN9_CzSA/hqdefault_live.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "STEEZYASFUCK",
        liveBroadcastContent: "live",
        publishTime: "2020-05-09T14:53:57Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "KeoC75csU4fGrMslfLFKHfuTpXE",
      id: {
        kind: "youtube#video",
        videoId: "lTRiuFIWV54",
      },
      snippet: {
        publishedAt: "2019-12-08T22:02:06Z",
        channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
        title: "1 A.M Study Session 📚 - [lofi hip hop/chill beats]",
        description:
          "Listen to 2 A.M Study Session : → https://www.youtube.com/watch?v=wAPCSnAhhC8 Download the illustration/animation (& support the artist) ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/lTRiuFIWV54/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/lTRiuFIWV54/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/lTRiuFIWV54/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "ChilledCow",
        liveBroadcastContent: "none",
        publishTime: "2019-12-08T22:02:06Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "c-7ZqqPpuP6Kn1VABTXD3UKo9do",
      id: {
        kind: "youtube#video",
        videoId: "kTL_hGa64Zo",
      },
      snippet: {
        publishedAt: "2020-05-17T22:00:16Z",
        channelId: "UC0fiLCwTmAukotCXYnqfj0A",
        title: "thinking about you ~ lofi hip hop mix",
        description:
          "Chill & relaxing lofi hip hop beats for when you're missing someone during quarantine Lofi / Chill Beats Cute & smooth mix Listen to another mix here ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/kTL_hGa64Zo/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/kTL_hGa64Zo/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/kTL_hGa64Zo/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "the bootleg boy",
        liveBroadcastContent: "none",
        publishTime: "2020-05-17T22:00:16Z",
      },
    },
    {
      kind: "youtube#searchResult",
      etag: "_vOx2ehWqgR10WuCdI5CD6cTUs4",
      id: {
        kind: "youtube#video",
        videoId: "5yx6BWlEVcY",
      },
      snippet: {
        publishedAt: "2020-03-21T13:21:02Z",
        channelId: "UCOxqgCwgOqC2lMqC5PYz_Dg",
        title: "Chillhop Radio - jazzy &amp; lofi hip hop beats 🐾",
        description:
          "Welcome to the Chillhop Radio, playing the best jazzy / lofi hip hop beats from our label to get you through your day. Enjoy your stay! Chillhop Radio ...",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/5yx6BWlEVcY/default_live.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/5yx6BWlEVcY/mqdefault_live.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/5yx6BWlEVcY/hqdefault_live.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Chillhop Music",
        liveBroadcastContent: "live",
        publishTime: "2020-03-21T13:21:02Z",
      },
    },
  ],
};

export const placeholderVideos = [
  {
    kind: "youtube#videoListResponse",
    etag: "CQF_u97cA7trYjBkuRfNLpwC69I",
    items: [
      {
        kind: "youtube#video",
        etag: "x5YqttmZDwpMJFedk2EB8HYsYNQ",
        id: "5qap5aO4i9A",
        snippet: {
          publishedAt: "2020-02-22T19:51:37Z",
          channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
          title: "lofi hip hop radio - beats to relax/study to",
          description:
            "Thank you for listening, I hope you will have a good time here :)\n\n🎼 Listen to the playlist on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n🧡 The Lofi Girl figure (limited edition)\n→ https://youtooz.com/products/lofi-girl\ufeff\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n🎧 Subscribe to my 2nd channel DreamyCow\n→ https://bit.ly/dreamy-cow\n\n💤 Listen to the sleepy radio\n→ http://bit.ly/sleepy-radio\n\n📌Update \n- 22/05/2020 New music added\n\n🎨 Illustration & Animation by Juan Pablo Machado\n→ https://bit.ly/Machadofb\n→ http://jpmachado.art\n\n📝 Submissions\n→ https://bit.ly/chilledcow-submissions",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/5qap5aO4i9A/default_live.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/5qap5aO4i9A/mqdefault_live.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/5qap5aO4i9A/hqdefault_live.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/5qap5aO4i9A/sddefault_live.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/5qap5aO4i9A/maxresdefault_live.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "ChilledCow",
          tags: [
            "lo-fi",
            "lo fi",
            "lofi",
            "lofi hiphop",
            "lo-fi hiphop",
            "lo fi hiphop",
            "hiphop",
            "hip hop",
            "lofi hip hop",
            "lo-fi hip hop",
            "lo fi hip hop",
            "lofi radio",
            "lo-fi radio",
            "lo fi radio",
            "lofi hip hop radio",
            "lo-fi hip hop radio",
            "lo fi hip hop radio",
            "chilledcow",
            "chilled cow",
            "chilledcow radio",
            "chilled cow radio",
            "chilledcow station",
            "lofi radio chilledcow",
            "chillhop",
            "study music",
            "lofi hip hop radio - beats to relax\\/study to",
            "beats to relax",
            "music to study",
            "radio",
            "relaxing music",
            "playlist",
            "music",
          ],
          categoryId: "10",
          liveBroadcastContent: "live",
          localized: {
            title: "lofi hip hop radio - beats to relax/study to",
            description:
              "Thank you for listening, I hope you will have a good time here :)\n\n🎼 Listen to the playlist on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n🧡 The Lofi Girl figure (limited edition)\n→ https://youtooz.com/products/lofi-girl\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n🎧 Subscribe to my 2nd channel DreamyCow\n→ https://bit.ly/dreamy-cow\n\n💤 Listen to the sleepy radio\n→ http://bit.ly/sleepy-radio\n\n📌Update \n- 22/05/2020 New music added\n\n🎨 Illustration & Animation by Juan Pablo Machado\n→ https://bit.ly/Machadofb\n→ http://jpmachado.art\n\n📝 Submissions\n→ https://bit.ly/chilledcow-submissions",
          },
        },
        statistics: {
          viewCount: "85277835",
          likeCount: "1448495",
          dislikeCount: "31151",
          favoriteCount: "0",
          commentCount: "0",
        },
      },
    ],
    pageInfo: {
      totalResults: 1,
      resultsPerPage: 1,
    },
  },
  {
    kind: "youtube#videoListResponse",
    etag: "PVCU9MeoSAlhZahX8m6KwebF1hk",
    items: [
      {
        kind: "youtube#video",
        etag: "AwcyiPwkgnjgs4fznjLdgfl_oMg",
        id: "DWcJFNfaw9c",
        snippet: {
          publishedAt: "2020-02-25T19:00:14Z",
          channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
          title: "lofi hip hop radio - beats to sleep/chill to",
          description:
            "Welcome to the sleepy lofi hip hop radio. This playlist contains the smoothest lofi hip hop beats, perfect to help you chill or fall asleep 💤\n\n🎼 Listen to the playlist on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n🧡 The Lofi Girl figure (limited edition)\n→ https://youtooz.com/products/lofi-girl\ufeff\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n🎧 Subscribe to my 2nd channel DreamyCow\n→ https://bit.ly/dreamy-cow\n\n📚 Listen to the 1st radio to help you study\n→ http://bit.ly/chilledcow-study\n\n📌Update \n- 22/05/2020 New beats added\n\n🎨 Illustration by Basile Gouttenoire\n→ https://www.artstation.com/bazart\n\n🎥 Animation by Nathalie Baraton\n→ https://www.instagram.com/nathalie.baraton/\n\n📝 Submissions\n→  https://bit.ly/chilledcow-submissions",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/DWcJFNfaw9c/default_live.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/DWcJFNfaw9c/mqdefault_live.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/DWcJFNfaw9c/hqdefault_live.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/DWcJFNfaw9c/sddefault_live.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/DWcJFNfaw9c/maxresdefault_live.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "ChilledCow",
          tags: [
            "lo-fi",
            "lo fi",
            "lofi",
            "lofi hiphop",
            "lo-fi hiphop",
            "lo fi hiphop",
            "hiphop",
            "hip hop",
            "lofi hip hop",
            "lo fi hip hop",
            "lofi radio",
            "lo-fi radio",
            "lo fi radio",
            "lofi hip hop radio",
            "lo fi hip hop radio",
            "chilledcow",
            "chilled cow",
            "chilledcow radio",
            "sleepy radio",
            "sleep radio",
            "lofi radio chilledcow",
            "chillhop",
            "study music",
            "beats to sleep",
            "sleep",
            "music to sleep",
            "radio",
            "sleepy music",
            "sleep music",
            "playlist",
            "music",
          ],
          categoryId: "10",
          liveBroadcastContent: "live",
          localized: {
            title: "lofi hip hop radio - beats to sleep/chill to",
            description:
              "Welcome to the sleepy lofi hip hop radio. This playlist contains the smoothest lofi hip hop beats, perfect to help you chill or fall asleep 💤\n\n🎼 Listen to the playlist on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n🧡 The Lofi Girl figure (limited edition)\n→ https://youtooz.com/products/lofi-girl\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n🎧 Subscribe to my 2nd channel DreamyCow\n→ https://bit.ly/dreamy-cow\n\n📚 Listen to the 1st radio to help you study\n→ http://bit.ly/chilledcow-study\n\n📌Update \n- 22/05/2020 New beats added\n\n🎨 Illustration by Basile Gouttenoire\n→ https://www.artstation.com/bazart\n\n🎥 Animation by Nathalie Baraton\n→ https://www.instagram.com/nathalie.baraton/\n\n📝 Submissions\n→  https://bit.ly/chilledcow-submissions",
          },
        },
        statistics: {
          viewCount: "13261160",
          likeCount: "246075",
          dislikeCount: "3469",
          favoriteCount: "0",
          commentCount: "0",
        },
      },
    ],
    pageInfo: {
      totalResults: 1,
      resultsPerPage: 1,
    },
  },
  {
    kind: "youtube#videoListResponse",
    etag: "VRlN-yzbBf65VAkTt7uqxDUDvK0",
    items: [
      {
        kind: "youtube#video",
        etag: "x4_Ac4MIfITq4FnBqkMTDp5HTkA",
        id: "eRCNLqg8wSI",
        snippet: {
          publishedAt: "2020-05-19T16:38:18Z",
          channelId: "UCYVyQv2rUtCMxJAFSuOSpmg",
          title: "Open Your MInd ~ lofi hip hop mix",
          description:
            "☊  Spotify playlist ( Tracks from this mix will be added to this playlist ) :\n● https://open.spotify.com/playlist/7LwAj4ZQyjbpVjbFk2LbNZ?si=0Wkc_FbMT-GCUhWb74zR8w\n\n→  lofi hip hop mix - beats to relax/study/sleep to \n→  [ study/sleep/homework music ]\n\n                                  ・ Dreamy ・ \n● Instagram :\n→ https://www.instagram.com/its_dreamy_yt/\n● Patreon ( Donate Support ) 🙏\n→ https://www.patreon.com/m/its_dreamy\n・・・\n👁   ART \n● by sarammir ( Sara Meseguer )\nhttps://www.instagram.com/sarammir/\nhttps://www.artstation.com/artwork/8KLkq\n\n ♪   TRACKLIST \n00:00   cxlt. - distance\n\nhttps://open.spotify.com/track/5JlF5Vd7rdR7REK4ET1vwc?si=kYmLFVyjT1-dWtLgnwdNqQ\nhttps://soundcloud.com/cxlt/distance-now-on-spotify\n\n01:23   obrabts - Pink - Lady\n\nhttps://open.spotify.com/track/0DmjTe8mVi2repQCU60DOo?si=jVBANDmPQ-SmfVVq_8rOjA\nhttps://soundcloud.com/user-390620681/2-pink-lady\n\n03:18   lawance - i wish this night was over\n\nhttps://open.spotify.com/track/2kYusVbdVFJ2iNLxOJPGo8?si=B1TvlRO9Sgy-e_3EdJOCqA\nhttps://soundcloud.com/user-800005999/i-wish-this-night-was-over\n\n04:39   Cammie - Daydreaming (feat Bert)\n\nhttps://open.spotify.com/track/2XCJMe05nOuFlaBHSHKHeA?si=JR-h4_-USxGI-QDRBmdn4Q\nhttps://soundcloud.com/cammiemusic/daydreaming-feat-bert\n\n06:46   Resident - Dreamers\n\nhttps://open.spotify.com/track/1JGQksT4ykEnAUxKabbh6S?si=vFgWE9FRShyZxJNkyQHMwg            \nhttps://soundcloud.com/raines-pollard/dreamers\n\n08:32   kainbeats - idyllic dreams (w_ mrneab)\n\nhttps://open.spotify.com/track/41ukhojDUq6lpOpHALi4sd?si=SwgPtCQ2Rd-kyWndm2VAGg\nhttps://soundcloud.com/kainbeats/idyllic-dreams\n\n10:01   Thaehan - Stay With Me\n\nhttps://open.spotify.com/track/0GPIlEs1BFkiuqgMFb3Cii?si=dmZPkCGXTXyJi1Ue7tcXCw\nhttps://soundcloud.com/loki-6/stay-with-me\n\n11:33   Sleepy Days - Summer Crossroads\n\nhttps://soundcloud.com/sleepy_days/summer-crossroads\n\n13:11   Chiccote's Beats - late afternoon\n\nhttps://open.spotify.com/track/74a6Z7Osg01ifkXioM8L6w?si=1AdZdbg7ThODtefKdLQ1tQ\nhttps://soundcloud.com/chiccotesbeats/a-sound-for-your-late-afternoon\n\n14:43   Emilioats - Youth\n\nhttps://open.spotify.com/track/4LYRChJpx7OzHNwUvfvB94?si=DDem55u5QlWLKgcnAbR4gQ\nhttps://soundcloud.com/emiliobeats/where-she-is\n\n17:27   Kosibeats - Waking Up At 6AM (feat Gilbeaux)\n\nhttps://open.spotify.com/track/5x1HPXNuzjze2oTkdGbtpt?si=hRP8HkK6QQCJk0ER8IxYug\nhttps://soundcloud.com/user-627660546/waking-up-at-6am-feat-gilbeaux\n\n18:58   Hevi - Endless Conversations\n\nhttps://open.spotify.com/track/2AlvsfYwnNAKKFMGWew0TI?si=OjyMD7X8T5CyOM88g1XBfw\nhttps://soundcloud.com/hevirain/tracks\n\n21:05   Emilioats - Runway\n\nhttps://open.spotify.com/track/5xOx17NFApN9hRzYHvJSv5?si=I07l51l1T9q5TzyffZyvLg\nhttps://soundcloud.com/emiliobeats/runway\n\n22:37   kanisan x no one's perfect - Pendulum\n                              *ChilledCow records\n\nhttps://open.spotify.com/track/1UW2cDI4KcNn2Zp0NVBIYV?si=CBJQfwKoTguhIvL2EQPG8A\nhttps://soundcloud.com/chilledcow/no-one-x-kanisan-a-way-of-existing\n\n26:05   miscél - Spells to fall asleep\n\nhttps://open.spotify.com/track/1kz8yR7pxHC24f50ZVgC6V?si=i8Mfhde0Tni0vehNdeOJ3A\nhttps://soundcloud.com/miscelbeets/spells-to-fall-asleep\n・・・・・・・・・・・・・・・・・・・・\n❗ Any claims of copyright infringement :\n✉ dre21amy@gmail.com\n・・・・・・・・・・・・・・・・・・・・\n📝 Submission :\nMusic:   https://soundcloud.com/its_dreamy\nArt:        dre21amy@gmail.com\n・・・・・・・・・・・・・・・・・・・・\n#Dreamy#lofi",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/eRCNLqg8wSI/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/eRCNLqg8wSI/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/eRCNLqg8wSI/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/eRCNLqg8wSI/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/eRCNLqg8wSI/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "Dreamy",
          tags: [
            "lofi hip hop mix",
            "lofi",
            "lofi hip hop",
            "lo fi",
            "lo-fi",
            "lofi hiphop",
            "lo-fi hip hop",
            "hip hop",
            "beats",
            "chill",
            "relax",
            "lofi type beat",
            "type beat",
            "shiloh",
            "kina",
            "joji",
            "lofi radio",
            "lofi mix",
            "mood",
            "chilledcow",
            "the bootleg boy",
            "happy lofi",
            "cute lofi",
            "3.30 am",
            "dreamy",
            "study chill beats",
            "lofi chill beats",
            "beat",
            "anime",
            "vibe",
            "instrumental",
            "lo-fi mix",
            "low fi",
            "lowfi",
            "japanese music",
            "gaming music",
            "chill mix",
            "chill out",
            "80´s",
            "90´s",
            "retro",
            "summer",
            "meditation",
            "music",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          defaultLanguage: "en-GB",
          localized: {
            title: "Open Your MInd ~ lofi hip hop mix",
            description:
              "☊  Spotify playlist ( Tracks from this mix will be added to this playlist ) :\n● https://open.spotify.com/playlist/7LwAj4ZQyjbpVjbFk2LbNZ?si=0Wkc_FbMT-GCUhWb74zR8w\n\n→  lofi hip hop mix - beats to relax/study/sleep to \n→  [ study/sleep/homework music ]\n\n                                  ・ Dreamy ・ \n● Instagram :\n→ https://www.instagram.com/its_dreamy_yt/\n● Patreon ( Donate Support ) 🙏\n→ https://www.patreon.com/m/its_dreamy\n・・・\n👁   ART \n● by sarammir ( Sara Meseguer )\nhttps://www.instagram.com/sarammir/\nhttps://www.artstation.com/artwork/8KLkq\n\n ♪   TRACKLIST \n00:00   cxlt. - distance\n\nhttps://open.spotify.com/track/5JlF5Vd7rdR7REK4ET1vwc?si=kYmLFVyjT1-dWtLgnwdNqQ\nhttps://soundcloud.com/cxlt/distance-now-on-spotify\n\n01:23   obrabts - Pink - Lady\n\nhttps://open.spotify.com/track/0DmjTe8mVi2repQCU60DOo?si=jVBANDmPQ-SmfVVq_8rOjA\nhttps://soundcloud.com/user-390620681/2-pink-lady\n\n03:18   lawance - i wish this night was over\n\nhttps://open.spotify.com/track/2kYusVbdVFJ2iNLxOJPGo8?si=B1TvlRO9Sgy-e_3EdJOCqA\nhttps://soundcloud.com/user-800005999/i-wish-this-night-was-over\n\n04:39   Cammie - Daydreaming (feat Bert)\n\nhttps://open.spotify.com/track/2XCJMe05nOuFlaBHSHKHeA?si=JR-h4_-USxGI-QDRBmdn4Q\nhttps://soundcloud.com/cammiemusic/daydreaming-feat-bert\n\n06:46   Resident - Dreamers\n\nhttps://open.spotify.com/track/1JGQksT4ykEnAUxKabbh6S?si=vFgWE9FRShyZxJNkyQHMwg            \nhttps://soundcloud.com/raines-pollard/dreamers\n\n08:32   kainbeats - idyllic dreams (w_ mrneab)\n\nhttps://open.spotify.com/track/41ukhojDUq6lpOpHALi4sd?si=SwgPtCQ2Rd-kyWndm2VAGg\nhttps://soundcloud.com/kainbeats/idyllic-dreams\n\n10:01   Thaehan - Stay With Me\n\nhttps://open.spotify.com/track/0GPIlEs1BFkiuqgMFb3Cii?si=dmZPkCGXTXyJi1Ue7tcXCw\nhttps://soundcloud.com/loki-6/stay-with-me\n\n11:33   Sleepy Days - Summer Crossroads\n\nhttps://soundcloud.com/sleepy_days/summer-crossroads\n\n13:11   Chiccote's Beats - late afternoon\n\nhttps://open.spotify.com/track/74a6Z7Osg01ifkXioM8L6w?si=1AdZdbg7ThODtefKdLQ1tQ\nhttps://soundcloud.com/chiccotesbeats/a-sound-for-your-late-afternoon\n\n14:43   Emilioats - Youth\n\nhttps://open.spotify.com/track/4LYRChJpx7OzHNwUvfvB94?si=DDem55u5QlWLKgcnAbR4gQ\nhttps://soundcloud.com/emiliobeats/where-she-is\n\n17:27   Kosibeats - Waking Up At 6AM (feat Gilbeaux)\n\nhttps://open.spotify.com/track/5x1HPXNuzjze2oTkdGbtpt?si=hRP8HkK6QQCJk0ER8IxYug\nhttps://soundcloud.com/user-627660546/waking-up-at-6am-feat-gilbeaux\n\n18:58   Hevi - Endless Conversations\n\nhttps://open.spotify.com/track/2AlvsfYwnNAKKFMGWew0TI?si=OjyMD7X8T5CyOM88g1XBfw\nhttps://soundcloud.com/hevirain/tracks\n\n21:05   Emilioats - Runway\n\nhttps://open.spotify.com/track/5xOx17NFApN9hRzYHvJSv5?si=I07l51l1T9q5TzyffZyvLg\nhttps://soundcloud.com/emiliobeats/runway\n\n22:37   kanisan x no one's perfect - Pendulum\n                              *ChilledCow records\n\nhttps://open.spotify.com/track/1UW2cDI4KcNn2Zp0NVBIYV?si=CBJQfwKoTguhIvL2EQPG8A\nhttps://soundcloud.com/chilledcow/no-one-x-kanisan-a-way-of-existing\n\n26:05   miscél - Spells to fall asleep\n\nhttps://open.spotify.com/track/1kz8yR7pxHC24f50ZVgC6V?si=i8Mfhde0Tni0vehNdeOJ3A\nhttps://soundcloud.com/miscelbeets/spells-to-fall-asleep\n・・・・・・・・・・・・・・・・・・・・\n❗ Any claims of copyright infringement :\n✉ dre21amy@gmail.com\n・・・・・・・・・・・・・・・・・・・・\n📝 Submission :\nMusic:   https://soundcloud.com/its_dreamy\nArt:        dre21amy@gmail.com\n・・・・・・・・・・・・・・・・・・・・\n#Dreamy#lofi",
          },
          defaultAudioLanguage: "en",
        },
        statistics: {
          viewCount: "66326",
          likeCount: "3137",
          dislikeCount: "24",
          favoriteCount: "0",
          commentCount: "250",
        },
      },
    ],
    pageInfo: {
      totalResults: 1,
      resultsPerPage: 1,
    },
  },
  {
    kind: "youtube#videoListResponse",
    etag: "x4vQinEwIJCNBufXc23eQqU1j1g",
    items: [
      {
        kind: "youtube#video",
        etag: "e0GtvrVDhkjCD3SfGl92YNHT6Jo",
        id: "-FlxM_0S2lA",
        snippet: {
          publishedAt: "2018-03-19T16:27:06Z",
          channelId: "UCSJ4gkVC6NrvII8umztf0Ow",
          title: "Lofi hip hop mix - Beats to Relax/Study to [2018]",
          description:
            "🎼 Listen to ChilledCow on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n📝 Submit your music\n→ https://bit.ly/chilledcow-submissions\n\nFull tracklist\n\n[00:00:00] idealism - last time\n[00:02:50] Philanthrope X Kupla - Cycles\n[00:05:25] bloopr - mondayloop [no friends, no worries]\n[00:06:50] leavv - within \n[00:09:30] leavv & misc.inc - Pictures (unreleased)\n[00:11:35] fortnight - 2000\n[00:13:03] Soho - At Peace\n[00:14:58] blnkspc_  - Sticky\n[00:18:30] j'san - in time (unreleased)\n[00:20:43] Dweeb -'72 Audi Coupe\n[00:21:45] sumwun - men cry\n[00:23:37] ṰṏỞ↑ἧᾯrṰḩ - over it\n[00:25:33] saiko - untitled (unreleased)\n[00:26:48] Saito & Lester, Nowhere - Glare (w/ otesla)\n[00:29:00] Philanthrope - Leavin'\n[00:31:08] hm SURF - Flunked This Semester \n[00:32:44] leavv - park walk\n[00:34:12] Kaizen 92´- lost n´ found\n[00:36:20] fortnight - 5AM\n[00:37:55] fortnight - the keys\n[00:39:41] Aeson - a l l u r e\n[00:42:15] Yaken & Nymano - Untitled (Unreleased)\n[00:44:26] Fortnight - Balcony settings\n[00:46:05] prima - Jin\n[00:47:25] Aeson - dreamin'\n[00:49:10] Leavv - Tomorrow (Chillhop Spring 2018)\n[00:51:52] asbeluxt - calming tea\n[00:53:07] BLVK. - affection (unreleased)\n[00:54:44] hm surf - Take Care\n[00:56:47] Psalm Trees - Wherever You Are (Chillhop Spring 2018)\n[00:58:47] Omaure - Honeypot\n[01:00:58] Joe Corfield - Wildflower (Chillhop Spring 2018)\n[01:03:18] ihaveaface - rainy/forest\n[01:05:13] hm surf - didn't get a switch for christmas\n[01:06:35] Orca Vibes - Intuition\n[01:08:20] Kaizen 92 - Magenta\n[01:09:45] Juan RIOS - Otoño\n[01:13:19] j'san - the voice inside my head (beat)\n[01:15:22] Peter Bark - L'aldilà\n[01:16:30] Philanthrope - Dromeda \n[01:18:41] charlie toØ human - moonlight love\n[01:21:58] saiko - bruh\n[01:23:45] chief - i am nobody\n[01:25:14] charlie toØ human - Autumn Daze\n[01:27:45] philanthrope - Blue w∕ drwn.\n[01:29:38] Aeson - smile\n[01:33:33] Omaure - Bunte Hunde (beat)\n[01:36:15] COMODO - 303\n[01:37:33] hm surf - 6am\n[01:39:17] mt. fujitive - trees\n[01:41:30] chief - tired\n[01:42:50] dweeb & too ugly - how you think (beat)\n[01:45:10] Clouds x HM Surf - Cloudsurfing \n[01:46:48] saiko - offtherecord\n[01:49:39] knowmadic - empty\n[01:52:13] sensi sye - no sleep\n[01:54:12] chief - stay\n[01:55:58] oatmello - inside (w/chief)\n[01:57:50] hm surf - corolla cruising (unreleased)\n\n🎶 Support the beatmakers\n\nhttps://soundcloud.com/idealismus (idealism)\nhttps://soundcloud.com/philanthrope1 (Philanthrope)\nhttps://soundcloud.com/kuplasound (Kupla)\nhttps://soundcloud.com/bloopr420 (b l o o p r)\nhttps://soundcloud.com/leavv (leavv.)\nhttps://soundcloud.com/miscinc (misc.inc)\nhttps://soundcloud.com/fortnight1 (fortnight)\nhttps://soundcloud.com/soundsbysoho (soho)\nhttps://soundcloud.com/b-side-production (B-side)\nhttps://soundcloud.com/tesk (TESK)\nhttps://soundcloud.com/iamjsan (j'san)\nhttps://soundcloud.com/beet_farmer (Dweeb)\nhttps://soundcloud.com/smwun (sumwun)\nhttps://soundcloud.com/countbazzy-2 (ṰṏỞ↑ἧᾯrṰḩ)\nhttps://soundcloud.com/saikotropic (saiko)\nhttps://soundcloud.com/bscsaito (Saito)\nhttps://soundcloud.com/arturofratini (Lester, Nowhere)\nhttps://soundcloud.com/tesla77 (OTESLA)\nhttps://soundcloud.com/hmsurf (hm SURF)\nhttps://soundcloud.com/bess-one (Kaizen 92´)\nhttps://soundcloud.com/a-e-s-t-r-o (Aeson)\nhttps://soundcloud.com/nymano (nymano)\nhttps://soundcloud.com/primabeats (prima)\nhttps://soundcloud.com/asbeluxt (asbeluxt)\nhttps://soundcloud.com/yungmai (BLVK.)\nhttps://soundcloud.com/psalm-trees (Psalm//Trees)\nhttps://soundcloud.com/omaure-1 (Omaure)\nhttps://soundcloud.com/joe-corfield-1 (Joe Corfield)\nhttps://soundcloud.com/ihaveaface (ihaveaface)\nhttps://soundcloud.com/orcavibes (Orca Vibes)\nhttps://soundcloud.com/juan-rios-beats (Juan RIOS)\nhttps://soundcloud.com/peterbark (PETER BARK)\nhttps://soundcloud.com/charlietoohuman (charlie toØ human)\nhttps://soundcloud.com/chieffrombmb (chief.)\nhttps://soundcloud.com/drwn_dot (drwn.)\nhttps://soundcloud.com/willgregory (COMODO)\nhttps://soundcloud.com/mt_fujitive (mt. fujitive)\nhttps://soundcloud.com/toouglyboi (too ugly)\nhttps://soundcloud.com/knowmadicbeats (knowmadic)\nhttps://soundcloud.com/sensisye (Sensi Sye)\nhttps://soundcloud.com/oatmello (oatmello)\n\n🎨 Artwork by Juan Pablo Machado\n→ https://www.facebook.com/machadoillustrator/\n→ http://machado.portfoliobox.io/\n→ http://jpmachado.art",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/-FlxM_0S2lA/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/-FlxM_0S2lA/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/-FlxM_0S2lA/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/-FlxM_0S2lA/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/-FlxM_0S2lA/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "ChilledCow",
          tags: [
            "chilledcow",
            "chilled cow",
            "lofi",
            "lofi hiphop",
            "lofi hip hop",
            "lo-fi hiphop",
            "lo fi hip-hop",
            "lofi mix",
            "lo-fi mix",
            "lofi hip hop mix",
            "lo-fi hip hop mix",
            "study",
            "study mix",
            "study music",
            "relax music",
            "relaxing music",
            "music to study",
            "study chill mix",
            "chillhop mix",
            "chilledcow mix",
            "chilled cow mix",
            "chill study beats",
            "beats",
            "chill beats",
            "study beats",
            "jazz",
            "chill jazz",
            "jazzhop",
            "study music mix",
            "concentration music",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "Lofi hip hop mix - Beats to Relax/Study to [2018]",
            description:
              "🎼 Listen to ChilledCow on Spotify, Apple music and more\n→ https://bit.ly/chilledcow-playlists\n\n👕 Check out the ChilledCow merch\n→ https://bit.ly/chilledcow-merch\n\n🌎 Follow ChilledCow everywhere\n→ https://bit.ly/chilledcow-instagram\n→ https://bit.ly/chilledcow-facebook\n→ https://bit.ly/chilledcow-twitter\n\n📝 Submit your music\n→ https://bit.ly/chilledcow-submissions\n\nFull tracklist\n\n[00:00:00] idealism - last time\n[00:02:50] Philanthrope X Kupla - Cycles\n[00:05:25] bloopr - mondayloop [no friends, no worries]\n[00:06:50] leavv - within \n[00:09:30] leavv & misc.inc - Pictures (unreleased)\n[00:11:35] fortnight - 2000\n[00:13:03] Soho - At Peace\n[00:14:58] blnkspc_  - Sticky\n[00:18:30] j'san - in time (unreleased)\n[00:20:43] Dweeb -'72 Audi Coupe\n[00:21:45] sumwun - men cry\n[00:23:37] ṰṏỞ↑ἧᾯrṰḩ - over it\n[00:25:33] saiko - untitled (unreleased)\n[00:26:48] Saito & Lester, Nowhere - Glare (w/ otesla)\n[00:29:00] Philanthrope - Leavin'\n[00:31:08] hm SURF - Flunked This Semester \n[00:32:44] leavv - park walk\n[00:34:12] Kaizen 92´- lost n´ found\n[00:36:20] fortnight - 5AM\n[00:37:55] fortnight - the keys\n[00:39:41] Aeson - a l l u r e\n[00:42:15] Yaken & Nymano - Untitled (Unreleased)\n[00:44:26] Fortnight - Balcony settings\n[00:46:05] prima - Jin\n[00:47:25] Aeson - dreamin'\n[00:49:10] Leavv - Tomorrow (Chillhop Spring 2018)\n[00:51:52] asbeluxt - calming tea\n[00:53:07] BLVK. - affection (unreleased)\n[00:54:44] hm surf - Take Care\n[00:56:47] Psalm Trees - Wherever You Are (Chillhop Spring 2018)\n[00:58:47] Omaure - Honeypot\n[01:00:58] Joe Corfield - Wildflower (Chillhop Spring 2018)\n[01:03:18] ihaveaface - rainy/forest\n[01:05:13] hm surf - didn't get a switch for christmas\n[01:06:35] Orca Vibes - Intuition\n[01:08:20] Kaizen 92 - Magenta\n[01:09:45] Juan RIOS - Otoño\n[01:13:19] j'san - the voice inside my head (beat)\n[01:15:22] Peter Bark - L'aldilà\n[01:16:30] Philanthrope - Dromeda \n[01:18:41] charlie toØ human - moonlight love\n[01:21:58] saiko - bruh\n[01:23:45] chief - i am nobody\n[01:25:14] charlie toØ human - Autumn Daze\n[01:27:45] philanthrope - Blue w∕ drwn.\n[01:29:38] Aeson - smile\n[01:33:33] Omaure - Bunte Hunde (beat)\n[01:36:15] COMODO - 303\n[01:37:33] hm surf - 6am\n[01:39:17] mt. fujitive - trees\n[01:41:30] chief - tired\n[01:42:50] dweeb & too ugly - how you think (beat)\n[01:45:10] Clouds x HM Surf - Cloudsurfing \n[01:46:48] saiko - offtherecord\n[01:49:39] knowmadic - empty\n[01:52:13] sensi sye - no sleep\n[01:54:12] chief - stay\n[01:55:58] oatmello - inside (w/chief)\n[01:57:50] hm surf - corolla cruising (unreleased)\n\n🎶 Support the beatmakers\n\nhttps://soundcloud.com/idealismus (idealism)\nhttps://soundcloud.com/philanthrope1 (Philanthrope)\nhttps://soundcloud.com/kuplasound (Kupla)\nhttps://soundcloud.com/bloopr420 (b l o o p r)\nhttps://soundcloud.com/leavv (leavv.)\nhttps://soundcloud.com/miscinc (misc.inc)\nhttps://soundcloud.com/fortnight1 (fortnight)\nhttps://soundcloud.com/soundsbysoho (soho)\nhttps://soundcloud.com/b-side-production (B-side)\nhttps://soundcloud.com/tesk (TESK)\nhttps://soundcloud.com/iamjsan (j'san)\nhttps://soundcloud.com/beet_farmer (Dweeb)\nhttps://soundcloud.com/smwun (sumwun)\nhttps://soundcloud.com/countbazzy-2 (ṰṏỞ↑ἧᾯrṰḩ)\nhttps://soundcloud.com/saikotropic (saiko)\nhttps://soundcloud.com/bscsaito (Saito)\nhttps://soundcloud.com/arturofratini (Lester, Nowhere)\nhttps://soundcloud.com/tesla77 (OTESLA)\nhttps://soundcloud.com/hmsurf (hm SURF)\nhttps://soundcloud.com/bess-one (Kaizen 92´)\nhttps://soundcloud.com/a-e-s-t-r-o (Aeson)\nhttps://soundcloud.com/nymano (nymano)\nhttps://soundcloud.com/primabeats (prima)\nhttps://soundcloud.com/asbeluxt (asbeluxt)\nhttps://soundcloud.com/yungmai (BLVK.)\nhttps://soundcloud.com/psalm-trees (Psalm//Trees)\nhttps://soundcloud.com/omaure-1 (Omaure)\nhttps://soundcloud.com/joe-corfield-1 (Joe Corfield)\nhttps://soundcloud.com/ihaveaface (ihaveaface)\nhttps://soundcloud.com/orcavibes (Orca Vibes)\nhttps://soundcloud.com/juan-rios-beats (Juan RIOS)\nhttps://soundcloud.com/peterbark (PETER BARK)\nhttps://soundcloud.com/charlietoohuman (charlie toØ human)\nhttps://soundcloud.com/chieffrombmb (chief.)\nhttps://soundcloud.com/drwn_dot (drwn.)\nhttps://soundcloud.com/willgregory (COMODO)\nhttps://soundcloud.com/mt_fujitive (mt. fujitive)\nhttps://soundcloud.com/toouglyboi (too ugly)\nhttps://soundcloud.com/knowmadicbeats (knowmadic)\nhttps://soundcloud.com/sensisye (Sensi Sye)\nhttps://soundcloud.com/oatmello (oatmello)\n\n🎨 Artwork by Juan Pablo Machado\n→ https://www.facebook.com/machadoillustrator/\n→ http://machado.portfoliobox.io/\n→ http://jpmachado.art",
          },
        },
        statistics: {
          viewCount: "33252954",
          likeCount: "460642",
          dislikeCount: "7800",
          favoriteCount: "0",
          commentCount: "15887",
        },
      },
    ],
    pageInfo: {
      totalResults: 1,
      resultsPerPage: 1,
    },
  },
];
